server:
  port: 8083

spring:
  application:
    name: comments
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.210.130:3307/Comment
    username: root
    password: 1234!
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #default_batch_fetch_size: 50

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
          jpa.JpaTransactionManager: DEBUG

eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.210.130:8761/eureka/


springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha

